// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xotyvmjzqiohbhgouigt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvdHl2bWp6cWlvaGJoZ291aWd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyODUxMzksImV4cCI6MjA2NDg2MTEzOX0.sDDdTbSWEn9h8Gw_xCSZEB-wBnWazaIiNAVjUilOPD8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);